// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dozaqjmdoblwqnuprxnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvemFxam1kb2Jsd3FudXByeG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NTU5ODAsImV4cCI6MjA2NTQzMTk4MH0.dOvT-HqqkUBXZTq3aRoiQZT5Je8Ejn-Bzy6ZqeTR_gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);